### PR TITLE
Refactor to reduce scope of variables

### PR DESCRIPTION
**Pull request by szabgab**

### CODE REVIEW

**Comment by wooorm** [comment]
Why? I think it’s highly likely that this doesn’t change anything speed/memory wise?

**Comment by szabgab** [comment]
Yeah, I don't know. I usually think it is better to reduce the scope of the variables to make it easier to understand the code. 
Especially the one that can be immutable.

In any case, I was just reading the code for my enjoyment. So feel free to leave this open or close this PR.

**Comment by wooorm** [comment]
It’s like this because it’s like the C version: https://github.com/wooorm/levenshtein.c/blob/ca084af84e591ec126093dc1607c235fbf00d6db/levenshtein.c#L27-L33

**Review by wooorm — APPROVED** [review]
fine to refactor this :+1:

**Comment by wooorm** [comment]
Thanks!

**Pull request merged**
